import Head from "next/head";
import Link from "next/link";
import type { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Message Board & Average Numbers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Test task made with{" "}
            <span className="text-[hsl(280,100%,70%)]">T3</span> Stack
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/task/numbers"
            >
              <h3 className="text-2xl font-bold">Average Numbers →</h3>
              <div className="text-lg">
                Enter a number and get a new average as a result of calculation
                with previously entered value
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/task/messages"
            >
              <h3 className="text-2xl font-bold">Messages →</h3>
              <div className="text-lg">
                Post your message so that others can see it too!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://github.com/samhainsamhainsamhain/message-desk"
            >
              <h3 className="text-2xl font-bold">Source Code →</h3>
              <div className="text-lg">Check out source code on my github</div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

// turn off layout for index page
Home.getLayout = function (page) {
  return page;
};
